### ISSUE TITLE
Annotations from iharited modules

### ISSUE THREAD

**Issue by vegegoku** [tbroyer/gwt-places#1]
What if i have the @WithTokonizer annotation inside an inherited module written by some one else, will this work too?

**Comment by tbroyer** [comment]
Ideally, it'd have been processed already and ship the generated class in the JAR. In case that's not the case, [JavaC](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html) can process already compiled classes (`javac -cp … -processorpath … -s … com.example.ClassToBeProcessed` – possibly combined with `-d` or `-proc:only`), or you could process the source file (but you'd have to extract  it from the JAR), without necessarily compiling it, through `-proc:only`)
